version: '3.8'
services:
  frontend:
    build:
      context: ./course-management
    ports:
      - "3000:80"
  
  backend:
    build:
      context: ./coursesapi
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/courses_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8080:8080"
  
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: courses_db
    ports:
      - "3306:3306"
